apiVersion: apps/v1
kind: Deployment
metadata:
  name: my-app-1
  labels:
    app: my-app-1
spec:
  replicas: 1
  selector:
    matchLabels:
      app: my-app-1
  template:
    metadata:
      labels:
        app: my-app-1
    spec:
      containers:
      - name: simple-express
        image: germanho112/simple-express
        ports:
        - containerPort: 8080
        livenessProbe:
          httpGet:
            path: /health
            port: 8080
          initialDelaySeconds: 3
          periodSeconds: 3
